### ISSUE TITLE
Donation links should be added to README.md

### ISSUE THREAD

**Issue by grantemsley** [BrianLima/HueHue#10]
You have them on Reddit, but should put them here too.  You deserve it!

I was just starting writing my own software for computer controlled RGB lighting with an Arduino when I stumbled across this.  With half the features I want already done! So instead of writing my own, I'm going to see what I can help improve here.

**Comment by BrianLima** [comment]
Hi, glad to hear that it is useful for you! I was currently busy with another minor project and a job change, so i didn't mess around with HueHue lately, and since it's in a incomplete stage, i don't want to be blatantly asking for donations, i want to make it more useful first.

If you have any doubts about the structure or ideas of things i should change on the software, tell me, i'll be happy to have someone to talk about those things.

**Comment by grantemsley** [comment]
So I'm trying to build it in visual studio 2017.  Following the instructions in build.md, I added the RGB.net feed `https://www.myget.org/F/rgb_net/api/v3/index.json` to the nuget package sources.

But it complains "Unable to find version 0.0.1.40 of package RGB.net".  It looks like the version that is available is 0.0.1

I'm not too familiar with using nuget so I have no idea how to fix that. What am I supposed to do?

**Comment by grantemsley** [comment]
@BrianLima The "Include prerelease" checkbox is checked.  I think maybe RGB.Net updated or rearranged their packages since the last time you updated the modules?

**Comment by BrianLima** [comment]
I just updated my origin with the latest RGB.Net from MyGet, you can try syncing your fork.

**Comment by grantemsley** [comment]
Thanks!  I get less errors now, but it still won't download all of them.

Error is:
Package 'RGB.Net.Devices.Msi.0.0.1.40' is not found on the source
